// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_generate from "./routes/api/generate.ts";
import * as $api_run from "./routes/api/run.ts";
import * as $index from "./routes/index.tsx";
import * as $Playground from "./islands/Playground.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/generate.ts": $api_generate,
    "./routes/api/run.ts": $api_run,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Playground.tsx": $Playground,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
